version: "3.8"

services:
  # ---------- PHP + Apache ----------
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html           # <‑‑ cambia el volumen a ./web
    depends_on:
      - db
      - flask_api                     # <‑‑ espera a que exista la API
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2

  # ---------- MySQL ----------
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ventas
      MYSQL_USER: panaderia
      MYSQL_PASSWORD: pan12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD:/docker-entrypoint-initdb.d

  # ---------- phpMyAdmin ----------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789

  # ---------- Flask + ONNX ----------
  flask_api:
    build: ./flask_api
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  mysql_data:
